POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email":"nejadabbasio@gmail.com",
    "password":"#aA12345678"
}

###
POST http://localhost:3000/auth/login HTTP/1.1
Content-Type: application/json

{
    "email":"nejadabbasio@gmail.com",
    "password":"#aA12345678"
}


###
GET http://localhost:3000/notes HTTP/1.1
Content-Type: application/json
Authorization: Bearer CfDJ8H8hfdbsG8ZAimjFKDQtuNEoJ_L6Ca_ihzKo7uoMEzx6COhQLyMGGt5Hbec70iA228ulhismILpyIKWkinKfa8j1VpSMbILc2fAi8_s53l6tzXDGqrutPlXjU3dT8-EExSr50h8BrfypWvn9J0FMomrOz9tdefTbg4HFcWM21wSnkYcJbqbj_4BdxGJCid1RdWbFL-6rWLygEuOp9a1gP4kLnlb-TsdvdCahU0fs2UYdvHxpqAVklTvLUhECWhqxEG2RU1CIN7_uNWAfJnnH-zBX4WJhCqf_OgRdUAx23ixkkh2nyJBTHZxY0Yut2TZDTTqIfpAW2MAYWyAYjNzUXN9EowIw8RsUqzKzRz-e6FDNHuSk4XNHS_yKvUureoKJxw8IgKFwQQdbgw827aeSXF0lWxSsnaaaLEo1EGayJqA8-q5kwe3pUWIKJG2ws756v9FtSUugyLZmjGR9km_Bf8RSga4DRdnUoac20dMjKYwnb_mYnBlVsU9It6q2pGuWa8ZGblpZaO9YTTj5XIBHavtJROXM0VlLlSVRibeqEvbvB610DiPgdXJnLfwkR6rCkLeMVIn2KUCd4Iaj_IktaB8