POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "username":"nejadabbasio@gmail.com",
    "password":"#aA12345678"
}

###
POST http://localhost:3000/auth/login HTTP/1.1
Content-Type: application/json

{
    "username":"nejadabbasio@gmail.com",
    "password":"#aA12345678"
}

#eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im5lamFkYWJiYXNpb0BnbWFpbC5jb20iLCJuYmYiOjE3MDcwMzk2NjAsImV4cCI6MTcwNzEyNjA2MCwiaWF0IjoxNzA3MDM5NjYwfQ.Mc3FJvuCHjIsSQPh3RNOwrHYe2YDeRmagXwAS0peBKE

###
GET http://localhost:3000/notes HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im5lamFkYWJiYXNpb0BnbWFpbC5jb20iLCJuYmYiOjE3MDcwNjI0NjUsImV4cCI6MTcwNzE0ODg2NSwiaWF0IjoxNzA3MDYyNDY1fQ.qBSwBBKQGpMTHOPPJGQDEZUEh2vs61USI_jGEDo_-FM