POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "username":"nejadabbasio2@gmail.com",
    "password":"#aA12345678"
}

###
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
    "email":"nejadabbasio@gmail.com",
    "password":"#aA12345678"
}


###
GET http://localhost:3000/notes HTTP/1.1
Content-Type: application/json
Authorization: Bearer CfDJ8H8hfdbsG8ZAimjFKDQtuNF8kYIuu7QJ4SiCogGyu36EkxZRpxEdWifwtlvm_5tAcoM1_a773jirYszxLPSehxSjSFCea2h4d9eZyP1RoaADpCSO8u4LEcsWeXiGXVBbo0OM4i9q7VlXal7-VHrRAeyAMvSE5mseYJ5SRWZRDJgZ3F2sFJqA17h-2AU9LUc5QD0IZjbvRE9VkKArLiUKB4krIO-ZcUPzEjDokQs3WnX2Q-BSGXAGyi4JqCPq3yzQ1MD3rL2-7ouxLFIPEiq5NuGylRqn-mbGZTTdyY27eUNCA80ywmTkaoWKFKNrDNMzMIrMk8eVcDY4cGHid5N8izOMhs7HPZ1fMH5JjL1-vpZu33fyeqJ_5bncQh3OMRcUCiKK562z99jzPVAznUGu46YV40eWwe1VuWN8zmAaHNCPNLuxl6dWxsDU6_GL4Sb0aaF8SUJ8owTmuCJ8vb4aJyR794hoI6b2k9NtzuVXh5qJBcJjQxorrVWXHUHuIQGSnDrFPv_uZA6Mk3yKnhKlqFhF0GhEU1jgl37fA9F8SRgFVRbfITKpzrZG1XZUm9P4IlzuCoDx2HfKRhh5moqj3gI